### ISSUE TITLE
[softdevice] out of timeslot access to TIMER0 

### ISSUE THREAD

**Issue by LuDuda** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#144]
It seems that current driver may access TIMER0 outside of its radio timeslot.

Problematic path:

`NRF_802154_RTC_IRQ_HANDLER(void)` -> `nrf_802154_lp_timer_synchronized()` ->         `nrf_802154_hp_timer_sync_prepare()` -> `nrf_timer_cc_write(TIMER0, ..)`

**Comment by hubertmis** [comment]
LP timer synchronization works only during timeslots by design. This problem was caused by SD RAAL bug.
