### ISSUE TITLE
Bug in RX/TX example in Wiki

### ISSUE THREAD

**Issue by dpiegdon** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#157]
I think the wiki/Sample-application has an error:
PAN ID is set to 0x04, 0x05, and short address is set to 0x06, 0x07.
But they are one byte too far. They should be 0x03, 0x04 and 0x05, 0x06.
As the 802.15.4 frame layout is this:

Byte: value
0,1: FSF
2: Seq# << this only has a single byte and there are no other fields.
3,4: Dest PAN ID
5,6: Dest. Addr
[...]

When I implement this in my own example, the above packet layout works, but not the examples layout.
See https://github.com/dpiegdon/nordic-template/tree/802.15.4

**Comment by dpiegdon** [comment]
Thanks :)
Glad I could help!

**Comment by hubertmis** [comment]
I've updated wiki according to suggestions.
