### ISSUE TITLE
Missing subdirectory in the nrf_802154_core.c include path

### ISSUE THREAD

**Issue by pszkotak** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#198]
Hello,

It seems that `mac_features` subdirectory is missing in the `nrf_802154_frame_parser.h` inclusion.
https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/blob/652a35c8718125ae7ef615df1155c5c412780b17/src/nrf_802154_core.c#L50

Kind regards,
Piotr

**Comment by hubertmis** [comment]
Fixed by #212
