### ISSUE TITLE
Signed/unsigned comparison in nrf_802154_ack_data.c

### ISSUE THREAD

**Issue by pszkotak** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#199]
Hello,

Please find the exact line below.

https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/blob/652a35c8718125ae7ef615df1155c5c412780b17/src/mac_features/ack_generator/nrf_802154_ack_data.c#L238

Kind regards,
Piotr

**Comment by hubertmis** [comment]
Closed by #211
