### ISSUE TITLE
Lint failure in nrf_802154_config.h in version v1.3.0

### ISSUE THREAD

**Issue by pszkotak** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#202]
Hello,
Please find log below.

```
#if RAAL_SOFTDEVICE || RAAL_REM

"*** LINT: ... sdk\nrf5\external\nRF-IEEE-802.15.4-radio-driver\src\nrf_802154_config.h(106) Warning 553: Undefined preprocessor variable 'RAAL_REM', assumed 0"
```

Kind regards,
Piotr

**Comment by hubertmis** [comment]
Hello,
in C undefined macro is evaluated to `false` in `#if` statement. It is perfectly ok. To suppress Lint warning I suggest to add -DRAAL_REM=0 to Lint build.
Kind regards,
Hubert

**Comment by pszkotak** [comment]
Thank you for the answer. Closing the issue.
