### ISSUE TITLE
channel_set function calling nrf_radio_frequency_set with channel instead of frequency

### ISSUE THREAD

**Issue by rs-development** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#223]
Thanks again for porting to the new nrf_radio.h.

The nrf_radio_frequency_set function takes the true frequency instead of the register value.

    __STATIC_INLINE void nrf_radio_frequency_set(uint16_t radio_frequency)
    {
        NRFX_ASSERT(radio_frequency <= 2500);

    #if defined(RADIO_FREQUENCY_MAP_Msk)
        NRFX_ASSERT(radio_frequency >= 2360);

        uint32_t delta;
        if (radio_frequency < 2400)
        {
            delta = ((uint32_t)(radio_frequency - 2360)) |
                    (RADIO_FREQUENCY_MAP_Low << RADIO_FREQUENCY_MAP_Pos);
        }
        else
        {
            delta = ((uint32_t)(radio_frequency - 2400)) |
                    (RADIO_FREQUENCY_MAP_Default << RADIO_FREQUENCY_MAP_Pos);
        }

        NRF_RADIO->FREQUENCY = delta;
    #else
        NRFX_ASSERT(radio_frequency >= 2400);
        NRF_RADIO->FREQUENCY = (uint32_t)(2400 - radio_frequency);
    #endif //defined(RADIO_FREQUENCY_MAP_Msk)
    }

channel_set functon calls with plain channel selection

    static void channel_set(uint8_t channel)
    {
        assert(channel >= 11 && channel <= 26);

        nrf_radio_frequency_set(5 + (5 * (channel - 11)));
    }

i would recommend to change the channel set function to

    static void channel_set(uint8_t channel)
    {
        assert(channel >= 11 && channel <= 26);

        nrf_radio_frequency_set(2405 + 5 * (channel - 11));
    }

**Comment by hubertmis** [comment]
Thanks for reporting this problem. We'll look into it soon.
