### ISSUE TITLE
Missing parenthesis in define NRF_802154_PPI_GROUPS_USED_MASK

### ISSUE THREAD

**Issue by mmrono** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#323]
The define for NRF_802154_PPI_GROUPS_USED_MASK is missing a closing parenthesis.
This is in nrf_802154_peripherals.h, lines 494-495:

`
#define NRF_802154_PPI_GROUPS_USED_MASK ((1 << NRF_802154_PPI_CORE_GROUP) | \
                                         (1 << NRF_802154_PPI_TIMESTAMP_GROUP)
`

**Comment by hubertmis** [comment]
Thanks for reporting this issue. Would you like to create a pull request to fix it?

**Comment by mmrono** [comment]
I don't think adding a single parenthesis would be much of a contribution :)
Probably simpler if you could add it.

**Comment by hubertmis** [comment]
Sure we can do that. I thought you have a commit ready. If not we'll fix it soon.

**Comment by hubertmis** [comment]
Fixed in #331
