### ISSUE TITLE
FEM pa control stays enabled after sending ACK frame

### ISSUE THREAD

**Issue by RR-Rico** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#6]
The version 1.x of the driver seems to be gone but I will still file that bug since it maybe affects the version 2 and I am hoping for a solution. I would like not to change driver versions.

Setup as following

- I am using driver version with this Hash: 8133edad60b0714118c3041654c3079b3cd799d5
- On Board is sending a message every 25ms (Intervall does not matter), no retries, just one message. 
- Another board is configured to recieve messages from that address. The front end module is configured with PA enable. And to send ACK frames. RAW Mode is used, if that matters.

- CH1-Yellow is the PA Enable Pin, Active high
- CH2-Green is toggeled if nrf_802154_received_raw is called
- CH4-Blue is toggeld if nrf_802154_tx_ack_started is called

The problem is that ACKs are only send after every 2nd message. At the Trigger, 3rd picture, everything seems to be working as expected.

1. The PA is enabled first
2. The nrf_802154_received_raw is send
3. And then nrf_802154_received_raw is called

But in the second picture the PA is enabled, but nrf_802154_tx_ack_started is never called. Still nrf_802154_received_raw is called, which should happen after the ACK is send. As shown in the wireshark screenshot below, ACKs or only send for every second frame.

Another issue is that the PA stays enabled untill another frame is recieved. Which will never happen in real world usage, since no frames could be recieved if the PA is enabled. I am assuming the messages are only recieved, since the PA is on an external board and there is quite some length to couple into the path between the nrf and the fem.

I hope someone can comment on that behavior.

![SCR06](https://user-images.githubusercontent.com/62379745/105033806-e4f7d080-5a58-11eb-900a-71f78ea5df3b.PNG)
![SCR08](https://user-images.githubusercontent.com/62379745/105033804-e45f3a00-5a58-11eb-9c6c-1c6a27d52fe4.PNG)
![SCR07](https://user-images.githubusercontent.com/62379745/105033808-e5906700-5a58-11eb-8dad-b46a140f51d5.PNG)

![image](https://user-images.githubusercontent.com/62379745/105034145-63ed0900-5a59-11eb-8189-9022c148f6ff.png)

**Comment by RR-Rico** [comment]
I just recognized, if LNA is enabled in the config, the PA pin is working as expected. Still an issue but someone with inside to the driver should be able to pinpoint the bug.

**Comment by hubertmis** [comment]
@RR-Rico, thanks for reporting this issue. I'm sorry for late reply, I've missed your message.

This problem should be fixed in the last release (1.9.0). Would it be possible for you to retest in this release?
